{
  "hash": "a17a256fffb20cd1cf1ae0ffa4168079",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Análisis Descriptivo\"\nformat: html\neditor: visual\n---\n\n\n## Llamado de librerias\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary (tidyverse)\nlibrary(ggplot2)\nlibrary(ggthemes)\nlibrary(dplyr)\nlibrary(gsheet)\n```\n:::\n\n\nA continuación se presentará una base de datos de las calificaciones que los estudiantes del cursos FIP 606 recibieron en las dos primeras pruebas cortas realizadas por el profesor Emerson Delponte\n\n\n::: {.cell}\n\n```{.r .cell-code}\nDatos <- gsheet2tbl(\"https://docs.google.com/spreadsheets/d/1bq2N19DcZdtax2fQW9OHSGMR0X2__Z9T/edit#gid=1092065531\")\n```\n:::\n\n\nVamos a realizar una visualizacion de los datos de manera general:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(Datos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     prova         pontos           nota       \n Min.   :1.0   Min.   : 6.00   Min.   : 42.90  \n 1st Qu.:1.0   1st Qu.:10.00   1st Qu.: 68.75  \n Median :1.5   Median :12.50   Median : 85.70  \n Mean   :1.5   Mean   :11.91   Mean   : 79.40  \n 3rd Qu.:2.0   3rd Qu.:14.00   3rd Qu.:100.00  \n Max.   :2.0   Max.   :16.00   Max.   :100.00  \n```\n\n\n:::\n:::\n\n\nCon esto, podemos entender que la nota menor es de 42.9, la mediana esta en 85.70, la media esta en 79.4 y hubieron pesonas con la calificacion mas alta.\n\n## Primero visualicemos las diferencias entre la primera prueba y la segunda.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nDatos|>\n  group_by(prova)|>\n  summarize(mean = mean(nota),\n            median =median(nota),\n            sd_mean= sd(nota),\n            minimo =min(nota),\n            max = max(nota))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 6\n  prova  mean median sd_mean minimo   max\n  <dbl> <dbl>  <dbl>   <dbl>  <dbl> <dbl>\n1     1  79.5   85.7    19.0   42.9   100\n2     2  79.3   84.4    19.7   43.8   100\n```\n\n\n:::\n:::\n\n\nUna vez comparadas, podemos entender que a vista de datos, no existe muchas diferencias entre los resultados de ambas pruebas.\n\nAhora, con esto podemos darnos cuenta de que las calificaciones estuvieron en un promedio mayor a 70 (tomando en cuenta que la desviacion es de +-19 puntos), sin embargo visualizar los datos de manera grafica puede ayudarnos a entender.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nDatos |>\n  ggplot(aes(prova,nota))+\n           geom_boxplot(color='black', fill='lightpink')+\n  ylim(0,100)+\n    labs(title= 'Frecuencia de las calificaciones',\n         subtitle = 'FIP606',\n       x= 'Nota',\n       y= 'Densidad')+\n  facet_wrap(~prova,scales = 'free_x')\n```\n\n::: {.cell-output-display}\n![](aula5_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nObservemos esto mismo en un grafico de violin\n\n\n::: {.cell}\n\n```{.r .cell-code}\nDatos|>\n  ggplot(aes(x= prova, y = nota))+\n           geom_violin()+\n    labs(title= 'Frecuencia de las calificaciones',\n         subtitle = 'FIP606',\n       x= 'Nota',\n       y= 'Densidad')+\n  theme_dark()+\n  facet_wrap(~prova,scales = 'free_x')\n```\n\n::: {.cell-output-display}\n![](aula5_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nAhora, observemos las frecuencias de los datos para la primera y segunda prueba.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nDatos|>\n  ggplot (aes(x = nota))+\n  geom_histogram(bins = 10,color=\"white\", fill =\"blue\")+\n    labs(title= 'Frecuencia de las calificaciones',\n         subtitle = 'FIP606',\n       x= 'Nota',\n       y= 'Densidad')+\n  xlim(30,110)+\n  facet_wrap(~prova)\n```\n\n::: {.cell-output-display}\n![](aula5_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nComo podemos observar, el grupo con mayor frecuencia esta en el rango de la maxima calificacion.\n\nAhora, para poder concluir este analisis, es importante saber cuantas calificaciones estan entre el rango de 70 a 100, por lo que con el siguiente codigo podemos hacerlo:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Total de datos prueba 1: 22\n#Total de datos prueba 2: 22\n\nCalificaciones1 <- sum(Datos$nota[Datos$prova == 1] >= 70 & Datos$nota[Datos$prova == 1] <= 100)\nCalificaciones2 <- sum(Datos$nota[Datos$prova == 2] >= 70 & Datos$nota[Datos$prova == 2] <= 100)\n\nprint('Cantidad de estudiantes que pasaron la prueba 1:')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Cantidad de estudiantes que pasaron la prueba 1:\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(Calificaciones1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 16\n```\n\n\n:::\n\n```{.r .cell-code}\nprint('Cantidad de estudiantes que pasaron la prueba 2:')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Cantidad de estudiantes que pasaron la prueba 2:\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(Calificaciones2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 13\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(\"Porcentaje de estudiantes que pasaron la prueba 1:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Porcentaje de estudiantes que pasaron la prueba 1:\"\n```\n\n\n:::\n\n```{.r .cell-code}\n16/22*100\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 72.72727\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(\"Porcentaje de estudiantes que pasaron la prueba 2:\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Porcentaje de estudiantes que pasaron la prueba 2:\"\n```\n\n\n:::\n\n```{.r .cell-code}\n13/22*100\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 59.09091\n```\n\n\n:::\n:::\n\n\nPor lo tanto, podemos concluir que para ambas pruebas, mas de la mitad de estudiantes pasaron los examenes cortos.\n\nLos estudiantes que pasaron la segunda prueba son menos de los que pasaron la primera prueba.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}