project:
  type: website
  output-dir: docs

execute: 
  cache: true
  freeze: auto
  
website:
  title: "FIP606"
  favicon: img/icon.png
  image: img/marypaz.png
  
  navbar:
    pinned: true
    logo: icon.png
     left:

      - text: Fundamentos
        menu:
          - href: Aula1.qmd
            text: Algumas funções do R
          - href: Aula2.qmd
            text: Importação e visualização dos dados
        
      - text: Visualização dos dados
        menu:
          - href: 
            text: Gráficos com ggplot
          - href: 
            text: Gráficos com ggplot - Parte 2
        
      - href: 
        text: Análise Descritiva
        
      - text: Análise Inferencial
        menu:
          - href: 
            text: Teste T e ANOVA
          - href: 
            text: ANOVA
          - href: 
            text: Análise de Modelo Misto, Correlação e Regressão Linear
            
      - href: 
        text: Criação de mapas   
      
      
      
    right: 
     - icon: github
       href: https://github.com/pazharvesteggplant
     - icon: instagram
       href: https://www.instagram.com/paz_harvest_eggplants/

  page-navigation: true
  page-footer: 
    center: "Copyright 2024, Mary Paz Romero Benavides"
    background: light

format:
  html:
    fontsize: 1.1em
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    warning: false

editor: visual


